spring.application.name=anima_BF_simulator

jasypt.encryptor.password=eljared

spring.datasource.url=jdbc:postgresql://localhost:5432/anima_bf_simulator
spring.datasource.username=jmarvie
spring.datasource.password=Aradilgalin669!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect