spring.application.name=anima_BF_simulator

jasypt.encryptor.password=eljared

spring.datasource.url=ENC(5mQDupTIf5XV36bKzt4chVI6FbLyv2Sw955r/KKTSydkoMEiu2yixh8Q2jyH2gwBrOHdbmvMy87uPAOguGTzGfBkwYmgxJQVFJcz99JbQCMYfYz3YCkSJputk6Lk01wL)
spring.datasource.username=ENC(m+CjnxsTUH01ZTAEr+/7Evaex3ZBS/PLOfS7A4YFUwpYG3dWOVpJ0dXqc5/eFEdD)
spring.datasource.password=ENC(bG/z/k/pH42JYzN3TPJIkC0nVOj6gYrID+TV/AYEtdirtYENn8U3pUfyjljytMYu)
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect